# Generated by Django 3.2.5 on 2021-07-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('semester', models.CharField(max_length=6)),
                ('unit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('middle_name', models.CharField(blank=True, max_length=250, null=True)),
                ('age', models.IntegerField()),
                ('date_of_brith', models.DateField()),
                ('level', models.IntegerField(choices=[(100, 'first'), (200, 'second'), (300, 'third'), (400, 'fourth'), (500, 'fifth'), (600, 'sixth')], default=100)),
                ('department', models.CharField(max_length=250)),
                ('faculty', models.CharField(max_length=250)),
                ('matric_no', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=6)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=5, null=True)),
                ('phone_no', models.IntegerField()),
            ],
            options={
                'ordering': ('-last_name', '-first_name', '-middle_name'),
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('middle_name', models.CharField(blank=True, max_length=250)),
                ('department', models.CharField(max_length=250)),
                ('faculty', models.CharField(max_length=250)),
                ('phone_no', models.IntegerField()),
                ('course', models.ManyToManyField(blank=True, to='StudentsMS.Course')),
                ('students', models.ManyToManyField(blank=True, related_name='students', to='StudentsMS.Student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='students_offered', to='StudentsMS.Student'),
        ),
    ]
